title: Sul's Coding Diary
author: sul lee
email: suerish.e@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Sul lee in Coding from the Basic.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://helloleesul.github.io/" # the base hostname & protocol for your site

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  # navigation:
    # - title: Diary
      # url: "/diary"
  disqus_shortname: helloleesul
  name: sul lee
  tagline: Web publisher.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml contents

  # generate social links in footer
  social_links:
    # twitter: 
    rss: rss
    # github: helloleesul
    # dribbble: 
    # facebook: 
    # flickr: 
    # instagram: littlemissweekend
    # linkedin: 
    # pinterest: 
    # youtube: 
    # telegram: 
    behance: leesul
    mySite: leesul

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed